all: longestN3 longestN2 longestNlogN longestN random gfg1 gfg2 longestNgfg longestNnew longestN_final

longestN_final: longestN_final.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longestN_final longestN_final.cpp

longestN3: longestN3.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longestN3 longestN3.cpp

longestN2: longestN2.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longestN2 longestN2.cpp

longestNlogN: longestNlogN.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longestNlogN longestNlogN.cpp

longestN:	longestN.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longestN longestN.cpp

random: random.cpp
	g++ random.cpp -o random

gfg1: gfg1.cpp
	g++ gfg1.cpp -o gfg1

gfg2: gfg2.cpp
	g++ gfg2.cpp -o gfg2

longestNgfg: longestNgfg.cpp
	g++ longestNgfg.cpp -o longestNgfg

longestNnew: longestNnew.cpp
	g++ longestNnew.cpp -o longestNnew
